name: ML-driven drifter data analysis
channels:
  - conda-forge
dependencies:
  - python=3.12
  - black
  - flake8
  - isort
  - scikit-learn
  - cmocean
  - cfeature
  - pickle
  - pip
  - typer
  - loguru
  - tqdm
  - pip:
    - python-dotenv
    - -e .